#!/bin/bash
UserDir=$HOME
download=$UserDir/Downloads
cd $download

mv *.txt "Arquivos de Texto"
mv *.pdf "Arquivos de Texto"
mv *.xlsb "Arquivos de Texto"
mv *.xls "Arquivos de Texto"
mv *.doc "Arquivos de Texto"
mv *.docx "Arquivos de Texto"
mv *.torrent Torrents
mv *.zip Compactados
mv *.tar.gz Compactados
mv *.tar.xz Compactados
mv *.rar Compactados
mv *.jpg "$UserDir/Imagens/Imagens Baixadas"
mv *.jpeg "$UserDir/Imagens/Imagens Baixadas"
mv *.gif "$UserDir/Imagens/Imagens Baixadas"
mv *.svg "$UserDir/Imagens/Imagens Baixadas"
mv *.png "$UserDir/Imagens/Imagens Baixadas"
mv *.exe "Executaveis"
mv *.otf $HOME/.fonts
mv *.deb "Executaveis"
mv *.sh "scripts baixados"
mv *.py "scripts baixados"
mv *.iso "Isos"
mv *.mp3 "$UserDir/Músicas"

if [[ $? -ne 0 ]]; then
  mv *.* "$UserDir/Downloads/sem categoria"
fi
