#!/bin/bash
UserDir=$HOME
download=$UserDir/Downloads
cd $download
echo $download

mv *.txt "Arquivos de Texto"
mv *.pdf "Arquivos de Texto"
mv *.xlsb "Arquivos de Texto"
mv *.xls "Arquivos de Texto"
mv *.doc "Arquivos de Texto"
mv *.docx "Arquivos de Texto"
mv *.torrent Torrents
mv *.zip Compactados
mv *.tar.gz Compactados
mv *.rar Compactados
mv *.jpg "$UserDir/Imagens/Imagens Baixadas"
mv *.jpeg "$UserDir/Imagens/Imagens Baixadas"
mv *.gif "$UserDir/Imagens/Imagens Baixadas"
mv *.svg "$UserDir/Imagens/Imagens Baixadas"
mv *.png "$UserDir/Imagens/Imagens Baixadas"
mv *.exe "Executaveis"
mv *.otf $HOME/.fonts
mv *.deb "Executaveis"
mv *.sh "scripts baixados"
mv *.py "scripts baixados"
mv *.iso "Isos"

