#!/bin/bash
echo "iniciando monitor_alsa.."
while true;do
	file=$(cat /tmp/alsa/log)
	if [[ $file != '' ]]
	then
		echo "restaurando configuração"
		alsactl --file "$HOME/.config/scripts/alsaconf/alsaconfig" restore
		echo "" > /tmp/alsa/log
	fi
	sleep 20
done
