#!/bin/bash
if [ $1 = "stop" ]
then
  echo "Desligando o servidor..."
  time(systemctl $1 apache2 && systemctl $1 mysql)
  echo "Servidor desligado."
  exit
elif [ $1 = "start" ]
then
  echo "Ligando o servidor..."
  time(systemctl $1 apache2 && systemctl $1 mysql)
  echo "Servidor ligado"
elif [ $1 = "vconf" ]
then
  runuser -l rodrigo -c "nvim /etc/apache2/apache2.conf"
elif [ $1 = "econf" ]
then
  sudo nvim /etc/apache2/apache2.conf
elif [ $1 = "--help" ]
then
  echo -e "As opções para esse script são:\n\nstop: desliga o servidor\n\nstart: inicia o servidor\n\nvconf: abre o arquivo de configuração do apache em modo de viusualização\n\neconf: abre o arquivo de configuração do apache em modo de edição\n\n--help: exibe esse conteúdo de ajuda"
else
  clear
  echo "Digite --help para ver mais opções"
fi

