#!/bin/bash
cd $HOME/.config/scripts
#--Scripts

./downloads-organizer

cd /home/rodrigo/.config/scripts/alsaconf
alsactl --file alsaconfig restore
#--Custom commands

cp $HOME/.zshrc $HOME/.config/scripts/.zshrc
