#!/usr/bin/python
import gi
import feedparser
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
#label.set_markup("Go to <a href=\"http://www.gtk.org\" ""title=\"Our website\">GTK+ website</a> for more")

feedlist= ["https://www.techspot.com/backend.xml","http://rss.uol.com.br/feed/jogos.xml"]

builder = Gtk.Builder()
builder.add_from_file("feed_model.glade")
window = builder.get_object("main_window")
image = builder.get_object("Img1")

fn1 = builder.get_object("FeedName1")
fname1 = feedparser.parse(feedlist[0])['feed']['title']
fnews1 = feedparser.parse(feedlist[0])['entries'][0]['link']
fn1.set_label(feedparser.parse(feedlist[0])['feed']['title'])
fn1.set_markup('<a href="%s">%s</a>' % (fnews1,fname1))

desc1 = builder.get_object("Description1")
desc1.set_label(feedparser.parse(feedlist[0])['entries'][0]['description'])

fn2 = builder.get_object("FeedName2")
fn2 = feedparser.parse(feedlist[1])['feed']['title'].replace('target="_blank"','')

window.move(0,0)
window.set_decorated(0)
window.show_all()

Gtk.main()


