#!/usr/bin/python2.7

import xml
import tkinter as tk
import time
import feedparser

feed = "https://www.techspot.com/backend.xml"

def show_window():
	window.attributes('-alpha','0.6')
	window.geometry("+0+0")

#def test():
#	window.attributes('-alpha','1')
#	window.geometry("-0+0")

rss=feedparser.parse(feed)
print rss.entries[1].summary_detail.value


window = tk.Tk()
window.overrideredirect(1)
lbl = tk.Label(window, text="Hello")
lbl.grid(column=0, row=0)
window.mainloop()
