#!/usr/bin/python2.7
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.set_default_size(1366,384)
window.connect("destroy", Gtk.main_quit)
Gtk.main()

