#!/usr/bin/python2.7
import gtk
import time
import feedparser

feed = ["https://www.techspot.com/backend.xml", "http://rss.home.uol.com.br/index.xml"]
rss = feedparser.parse(feed[1])

print rss.entries[1].summary_detail.value
print rss.entries[0].title


class PyApp(gtk.Window):
    # inicia a janela gtk automaticamente
    def __init__(self):
        type(super(PyApp, self).__init__())
        self.set_default_size(1366, 384)
        self.move(0, 0)
        self.set_title("Hello World in PyGTK")
        btn_link = gtk.LinkButton(rss.entries[1].link, rss.entries[1].title)
        print btn_link.props
        self.add(btn_link)
        self.set_decorated(0)
        self.show_all()


class conta():
    def __init__(self):
        self.multiplicar(c,d)

    def multiplicar(self, a, b):
        # feed = ["https://www.techspot.com/backend.xml", "http://rss.home.uol.com.br/index.xml"]
        # rss = feedparser.parse(feed[1])
        print a * b


PyApp()
gtk.main()
