import pyautogui as bot
from time import sleep
from random import randint as random
from pyperclip import paste
from pyperclip import copy

bot.moveTo(125, 41, duration=1)
bot.click()
bot.moveTo(70, 257, duration=1)
bot.scroll(-10)

bot.moveTo(144, 130, duration=1)
bot.click()
bot.moveTo(272, 198, duration=1)
bot.click()
bot.moveTo(138, 533, duration=1)
bot.click()
sleep(1)
bot.hotkey('shift', 'f10')
sleep(.25)
bot.press('enter')
arr = paste().split("/")
name = arr[len(arr)-1].split(".")[0]
copy("Camisa %s" % name)
bot.moveTo(1122, 738, duration=1)
bot.click()
bot.moveTo(282, 224, duration=1)
bot.click()
bot.hotkey('ctrl', 'v')
bot.moveTo(204, 315, duration=1)
bot.click()
copy("Uma linda Camiseta do %s" % name)
bot.hotkey('ctrl', 'v')
bot.moveTo(124, 402, duration=1)
bot.click()
copy(str(random(100, 300)))
bot.hotkey('ctrl', 'v')
bot.moveTo(135, 477, duration=1)
bot.click()
copy(str(random(10,100)))
bot.hotkey('ctrl', 'v')
bot.moveTo(95, 663, duration=1)
bot.click()
for i in range(19):
    sleep(2)
    bot.scroll(-10)
    bot.moveTo(197, 140, duration=1)
    bot.click()
    bot.moveTo(162, 191, duration=1)
    bot.click()
    bot.moveTo(153, 527, duration=1)
    bot.click()
    sleep(1)
    for i in range(i+1):
        bot.press('down')
    sleep(.2)
    bot.hotkey('shift', 'f10')
    sleep(.2)
    bot.press('enter')
    arr = paste().split("/")
    name = arr[len(arr) - 1].split(".")[0]
    bot.moveTo(1134, 741, duration=1)
    bot.click()
    bot.moveTo(144, 216, duration=1)
    bot.click()
    copy("Camisa do %s" % name)
    bot.hotkey('ctrl', 'v')
    bot.moveTo(160, 306, duration=1)
    bot.click()
    copy("Uma Linda Camiseta do %s" % name)
    bot.hotkey('ctrl', 'v')
    bot.moveTo(174, 386, duration=1)
    bot.click()
    copy(str(random(100,300)))
    bot.hotkey('ctrl', 'v')
    bot.moveTo(156, 478, duration=1)
    bot.click()
    copy(str(random(10,100)))
    bot.hotkey('ctrl', 'v')
    bot.moveTo(92, 662, duration=1)
    bot.click()

